# Generated by Django 5.1.1 on 2024-10-25 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_vehiculo_modelo_alter_vehiculo_monto_mecanico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mecanico',
            name='monto_mecanico',
            field=models.IntegerField(default=0),
        ),
    ]
