# Generated by Django 5.1.1 on 2024-11-14 23:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_vehiculo_estado_alter_vehiculo_fecha_salida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='created',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='updated',
        ),
        migrations.AlterField(
            model_name='inventario',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='tipo_vehiculo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='VehiculoEnEspera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('esperando', 'Esperando'), ('en_proceso', 'En Proceso'), ('completado', 'Completado')], default='esperando', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_estimacion', models.DateTimeField(blank=True, null=True)),
                ('repuestos', models.ManyToManyField(to='app.inventario')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.vehiculo')),
            ],
        ),
    ]
