# Generated by Django 5.1.1 on 2024-11-15 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_vehiculo_created_remove_vehiculo_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='precio',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='monto_total',
            field=models.IntegerField(default=0),
        ),
    ]
