# Generated by Django 5.1.1 on 2024-11-20 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_fecha_solicitud_vehiculoenespera_fecha_llegada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='repuesto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.inventario'),
        ),
    ]
