# Generated by Django 5.1.1 on 2024-11-26 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_bombero'),
    ]

    operations = [
        migrations.AddField(
            model_name='bombero',
            name='descripcion',
            field=models.CharField(default='Sin descripción', max_length=255),
        ),
        migrations.AddField(
            model_name='bombero',
            name='nombre',
            field=models.CharField(default='Sin nombre', max_length=100),
        ),
    ]
