# Generated by Django 5.1.1 on 2024-11-26 05:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_bombero_descripcion_bombero_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehiculoCompleto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_vehiculo', models.CharField(max_length=50)),
                ('patente', models.CharField(max_length=200)),
                ('fecha_llegada', models.DateTimeField(default=django.utils.timezone.now)),
                ('reparacion', models.CharField(max_length=100)),
                ('monto_mecanico', models.IntegerField(default=0)),
                ('monto_total', models.IntegerField(default=0)),
                ('fecha_salida', models.DateTimeField(blank=True, null=True)),
                ('mecanico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.mecanico')),
            ],
        ),
    ]
