# Generated by Django 5.1.1 on 2024-11-29 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudBombero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bombero', models.CharField(max_length=50)),
                ('tipo_vehiculo', models.CharField(max_length=50)),
                ('patente', models.CharField(max_length=200)),
                ('fecha_salida', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='vehiculoenespera',
            old_name='Repuesto',
            new_name='repuesto',
        ),
    ]
