# Generated by Django 5.1.3 on 2024-12-02 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_boleta_fecha_llegada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudbombero',
            name='fecha_salida',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='fecha_llegada',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='fecha_salida',
        ),
        migrations.RemoveField(
            model_name='vehiculocompleto',
            name='fecha_llegada',
        ),
        migrations.RemoveField(
            model_name='vehiculocompleto',
            name='fecha_salida',
        ),
        migrations.RemoveField(
            model_name='vehiculoenespera',
            name='fecha_llegada',
        ),
    ]
