# Generated by Django 5.1.1 on 2024-12-03 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_boleta_fecha_llegada_solicitudbombero_fecha_salida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculoenespera',
            name='fecha_salida',
            field=models.DateField(default='2024-12-02'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='boleta',
            name='fecha_llegada',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_llegada',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='solicitudbombero',
            name='fecha_salida',
            field=models.DateField(default='2024-12-02'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='fecha_llegada',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='fecha_salida',
            field=models.DateField(default='2024-12-02'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehiculocompleto',
            name='fecha_llegada',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='vehiculocompleto',
            name='fecha_salida',
            field=models.DateField(default='2024-12-02'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehiculoenespera',
            name='fecha_llegada',
            field=models.DateField(),
        ),
    ]
