# Generated by Django 5.1.1 on 2024-12-03 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_vehiculoenespera_fecha_salida_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculoenespera',
            name='fecha_salida',
        ),
    ]
