# Generated by Django 5.1.1 on 2024-12-03 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_vehiculoenespera_fecha_salida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculocompleto',
            name='fecha_salida',
            field=models.DateField(null=True),
        ),
    ]
