# Generated by Django 5.1.1 on 2024-12-03 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_vehiculocompleto_fecha_salida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculoenespera',
            name='fecha_salida',
        ),
    ]
